# Generated by Django 3.0 on 2021-05-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
    ]
